name: Delete Package (container)

on:
  #push:
  #  paths-ignore:
  #    - '**.md'
  #    - 'LICENSE'
  workflow_dispatch: # 手动执行时候可以配置的参数
    inputs:
      pkgName:
        description: 'Delete pkg name'
        type: choice
        default: "ffmpeg-builds/base"
        required: false
        options: 
        - ffmpeg-builds/base
        - ffmpeg-builds/base-win64
        - ffmpeg-builds/win64-gpl
        - ffmpeg-builds/win64-lgpl
        - ffmpeg-builds/win64-gpl-shared
        - ffmpeg-builds/win64-lgpl-shared
env:
  DOCKER_BUILDKIT: 1

jobs:
  del_pkg:
    name: Delete packages
    if: ${{ github.event.inputs.pkgName != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: actions/delete-package-versions@v5
        with: 
          owner: 'indiff'
          package-name: "${{ github.event.inputs.pkgName }}"
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'false'
